### PR TITLE
Geometry

### PR DESCRIPTION
**Pull request by artemp**

### CODE REVIEW

**Comment by mourner** [comment]
@artemp could you change the formatting so that it respects the [clang-format options](https://github.com/mapbox/geojson-vt-cpp/blob/master/.clang-format) in the repo, or do you think we should change the repo options?

**Comment by artemp** [comment]
@mourner - Agree, we should respect local `clang-format` but this particular needs updating I think. Maybe a good time to at least try using a similar formatting across projects 
/cc @daniel-j-h

**Comment by mourner** [comment]
cc @kkaefer who committed the initial settings as far as I remember. Let's stick to the current ones but switch when we agree on better settings across projects.

**Comment by kkaefer** [comment]
@artemp it's the same formatting we use in in mapbox-gl-native. Any reasons to change it?

**Comment by daniel-j-h** [comment]
Capturing from chat with @artemp yesterday: it's quite hard to get consistent formatting across the board, mostly due to different clang-format versions.

For example, it seems like clang-format-3.8 re-orders includes by default, older versions do not. This can be solved by dumping a config from clang-format 3.8 / HEAD and then disabling all new features to be backwards compatible.

This is a huge mistake on the clang-format devs side in my opinion.

**Comment by artemp** [comment]
@kkaefer -  I didn't realise this style is used in mapbox-gl-native,  lets leave it here as it is for now. Hopefully we can all agree to something we can all share across projects but as @daniel-j-h mentioned above current situation with `clang-format' is not very encouraging. 
 
```c++
LonLat(std::array<double, 2> const& coordinates) : lon(coordinates[0]), lat(coordinates[1]) {
}
```
I personally find this particular formatting a bit weird ^ , could be just me :)

**Pull request merged**
