### PR TITLE
expose public API symbols with default visibility attribute

### PR DESCRIPTION
**Pull request by mikemorris**
Refs https://github.com/mapbox/mapbox-gl-native/pull/2584#issuecomment-151611352

/cc @1ec5

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I believe it's better to tag the classes rather than individual methods. @springmeyer is that correct?

**Comment by mikemorris** [comment]
My intent was to limit the scope to only the public methods in each class @jfirebaugh, not sure on best practice here.

**Comment by springmeyer** [comment]
> I believe it's better to tag the classes rather than individual methods. @springmeyer is that correct?

Yes, in the sense that all we tag in Mapnik is the classes and never had any trouble.

So, I think the `class GEOJSONVT_PUBLIC Convert` is correct and makes obsolete/unneeded the usage of `__attribute__ ((used)) static std::vector<ProjectedFeature> convert`. I think that  `__attribute__ ((used))` should be removed since it is not doing anything.

**Comment by mikemorris** [comment]
Yea, `__attribute__ ((used))` doesn't seem like it's doing anything useful @springmeyer. My current problem is that the compiler/linker seems to be not picking up the symbols from `libgeojsonvt.a` (maybe because it thinks it doesn't need them?) when running `make ipackage`, despite including [`<@(geojsonvt_static_libs)`](https://github.com/mapbox/mapbox-gl-native/blob/geojsonvt-2.1.6/gyp/core.gypi#L51) in `gyp/core.gypi` and even trying to manually merge the static libs together like [what's happening with libuv](https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/ios/package.sh#L80).

Output from `nm`: https://gist.github.com/mikemorris/5480c9668ebd15cfd4d6

**Comment by mikemorris** [comment]
We could keep `-fvisibility=hidden` and expose the `GeoJSONVT` and `Convert` classes, but switching back to `-fvisibility-inlines-hidden` seems to be sufficient now that https://github.com/mapbox/mapbox-gl-native/pull/2584 is back to `-fvisibility-inlines-hidden` as well.

**Comment by jfirebaugh** [comment]
`-fvisibility=hidden` with public symbols explicitly tagged is the right way to go, and a convention that we should follow for all (non-header only) Mapbox libraries.

**Comment by jfirebaugh** [comment]
Let's tag all of the headers in `geojson-vt-cpp/include/mapbox` -- their presence in this directory indicates they are public.

**Pull request merged**
