### PR TITLE
Refactor geometry types

### LINKED ISSUE #18: Check variant type with is<T>() before calling get<T>()
Especially https://github.com/mapbox/geojson-vt-cpp/blob/v2.1.6.3/src/geojsonvt_convert.cpp#L310, from segfault in https://github.com/mapbox/mapbox-gl-native/issues/2926

### PR DESCRIPTION
**Pull request by mourner**
Makes types used in GeoJSON-VT more explicit, predictable and memory-efficient, and avoids deep nesting completely. Closes #18 (in theory) and #19. I'd really appreciate a review since this is my first dive into C++ in quite a while. 

Would also be cool to set up a benchmark to compare master with this one on some big GeoJSON file. @incanus do you have a benchmark script handy? I remember you running some samples a while ago.

I also need to do some DRYing in `geojsonvt_convert.cpp` since there's still a lot of copypasted code, and there are some unhandled invalid GeoJSON cases that produce segmentation fault.

Update: additionally fixes formatting (clang-format) and various bad practices (clang-tidy).

cc @kkaefer @mikemorris @incanus @jfirebaugh

### CODE REVIEW

**Comment by jfirebaugh** [comment]
The type changes look good to me. If you wanted to go even further with strict typing, you could eliminate `ProjectedFeatureType` in favor of something like:

```
class ProjectedPointFeature {
  ProjectedPoint geometry;
  ...
};

class ProjectedLineStringFeature {
  ProjectedPoints geometry;
  ...
};

class ProjectedPolygonFeature {
  ProjectedRings geometry;
  ...
};

using ProjectedFeature = mapbox::variant<
  ProjectedPointFeature,
  ProjectedLineStringFeature,
  ProjectedPolygonFeature>;
```

**Comment by mourner** [comment]
@jfirebaugh good suggestion, looking into it.

**Comment by mourner** [comment]
Good news: this branch improves performance by about 70%. The 100MB zips GeoJSON is indexed in ~4s compared to ~7s in master.
Bad news: still much slower than JS, which does the same in 1.3s. We can do better :)

**Comment by mourner** [comment]
Disregard the last sentence! 4s above includes JSON parsing, while the JS version actually takes 3.7s parsing + 3.3s indexing. So the C++ version is roughly 70% faster than JS!

**Pull request merged**
